/**
 * Strings PT-BR do marketplace (/marketplace/*).
 * Mesmas chaves que `es` / `en` em i18n.ts.
 */
export const MARKETPLACE_STRINGS_PT: Record<string, string> = {
  "sec.market.kicker": "Marketplace HRS / Hashrate Space",
  "sec.market.h2": "Equipamentos e infraestrutura",
  "sec.market.desc":
    "Catálogo de referência para hospedagem e serviços. Solicite orçamento ou catálogo por e-mail.",
  "filter.aria": "Filtrar por categoria",
  "market.catalog": "Solicitar catálogo",
  "mail.subject.catalog": "Solicitação de catálogo — Marketplace",
  "mail.subject.request": "Consulta sobre produto — Marketplace",
  "shelf.request": "Consultar",
  "modal.close": "Fechar",
  "modal.title": "Consulta sobre produto",
  "modal.hint": "Envie-nos os detalhes do que precisa ou use o link de e-mail.",
  "filter.cat.infra": "Infraestrutura",
  "filter.cat.cabling": "Cabeamento",
  "filter.cat.cooling": "Refrigeração",
  "filter.cat.software": "Software",
  "filter.cat.services": "Serviços",
  "filter.cat.general": "Outros",
  "price.from": "A partir de",

  "nav.home": "Início",
  "nav.services": "Serviços",
  "nav.equipment": "Equipamentos",
  "nav.faq": "FAQ",
  "nav.company": "Empresa",
  "nav.contact": "Contato",
  "header.logo_aria": "Hashrate Space início",
  "header.cart": "Carrinho",
  "header.cart_open": "Abrir carrinho de orçamentos",
  "header.cart_empty": "Carrinho vazio",
  "header.cart_units": "Carrinho: {{n}} unidades na lista",
  "header.cart_units_many": "Carrinho: mais de 99 unidades na lista",
  "header.menu": "Menu",
  "header.register": "Cadastro",
  "header.logout": "Sair",
  "header.lang_es": "ES",
  "header.lang_en": "EN",
  "header.lang_pt": "PT",
  "header.lang_hint": "Idioma",

  "footer.strip_region": "Rodapé do site",
  "footer.brand_slogan":
    "Plataforma de infraestrutura de alto desempenho para mineração de Bitcoin.",
  "footer.col_company": "Empresa",
  "footer.col_media": "Mídia",
  "footer.col_social": "Social",
  "footer.media.site": "Hashrate.space",
  "footer.media.video": "Vídeo institucional",
  "footer.social.instagram": "Instagram — Hashrate Space",
  "footer.social.linkedin": "LinkedIn — Hashrate Space",
  "footer.social.x": "X (Twitter) — Hashrate Space",
  "footer.sgi": "Sistema de Gestão Interna (SGI)",
  "footer.copyright": "© {{year}} Hashrate Space. Todos os direitos reservados.",

  "catalog.kicker": "Loja online",
  "catalog.intro": "Escolha seu equipamento, preencha o carrinho e faça seu pedido.",
  "catalog.fallback_note":
    "Se não encontrar o modelo que procura, fale conosco: atualizamos o catálogo com frequência.",
  "catalog.syncing": "Sincronizando catálogo com o servidor…",
  "catalog.add_short": "+ Adicionar equipamento",

  "corp.hero.title": "Plataforma de infraestrutura de alto desempenho para mineração de Bitcoin",
  "corp.hero.lede":
    "Datacenters, energia, suporte técnico e operação profissional. Tudo gerenciado para que você foque no resultado.",
  "corp.hero.cta_shop": "Ver equipamentos na loja",
  "corp.hero.cta_contact": "Ir para contato",
  "corp.stat.security": "Segurança",
  "corp.stat.security_val": "24 / 7",
  "corp.stat.dc": "Datacenters",
  "corp.stat.dc_val": "4",
  "corp.stat.mw": "Megawatts",
  "corp.stat.mw_val": "+ 20",
  "corp.stat.miners": "Mineradores hospedados",
  "corp.stat.miners_val": "+ 5400",
  "corp.featured.title": "Equipamentos mais procurados",
  "corp.featured.desc": "Catálogo ASIC atualizado: orçamento online com sua conta.",
  "corp.featured.cta": "Abrir catálogo",
  "corp.hosting.title": "Serviço tudo incluído",
  "corp.hosting.body":
    "Os planos de hospedagem da Hashrate Space são tarifas tudo-em-um: espaço em rack, suporte direto, operação com resolução de incidentes menores, atualizações de firmware e técnicos no local para manutenção da infraestrutura — fornecimento elétrico, refrigeração e rede de TI.",
  "corp.spotlight.tag1": "Novo",
  "corp.spotlight.title": "BITMAIN ANTMINER Z15 PRO",
  "corp.spotlight.body":
    "O equipamento de mineração do momento! Compre e instale já em nossos datacenters e comece a minerar Zcash.",
  "corp.spotlight.specs_aria": "Especificações Antminer Z15 Pro",
  "corp.spotlight.spec_v1": "840 kSol/s",
  "corp.spotlight.spec_l1": "Hashrate nominal",
  "corp.spotlight.spec_v2": "2900 W",
  "corp.spotlight.spec_l2": "Consumo elétrico",
  "corp.spotlight.spec_v3": "3,3 J/kSol",
  "corp.spotlight.spec_l3": "Eficiência energética",
  "corp.spotlight.cta": "Ver na loja",
  "corp.spotlight.zcash_logo_alt": "Logo Zcash (ZEC)",
  "corp.spotlight.img_alt": "Antminer Z15 Pro — mineração Equihash / Zcash (ZEC)",
  "corp.best_selling.title": "Equipamentos mais vendidos",
  "corp.market_shortcuts_aria": "Atalhos do marketplace — abrir ficha do equipamento",
  "corp.mp_card_link_aria": "Abrir no marketplace",
  "corp.play_video": "Assistir ao vídeo",
  "corp.play_video_close": "Fechar vídeo",
  "corp.metrics.tech": "Equipe",
  "corp.form.name": "Nome",
  "corp.form.last_name": "Sobrenome",
  "corp.form.email": "E-mail",
  "corp.form.subject": "Assunto",
  "corp.form.phone": "Telefone",
  "corp.form.message": "Mensagem",
  "corp.form.submit": "Enviar",
  "corp.form.hint":
    "Seu cliente de e-mail será aberto com a mensagem. Você também pode nos escrever diretamente em sales@hashrate.space.",
  "corp.contact.social": "Redes sociais",
  "corp.contact.headquarter": "Sede",
  "corp.strip.tagline": "Plataforma de infraestrutura de alto desempenho e operação ponta a ponta",
  "corp.strip.services": "Serviços",
  "corp.strip.equipment": "Equipamentos",
  "corp.strip.investors": "Investidores",
  "corp.strip.write_us": "Fale conosco",
  "corp.metrics.years": "Anos de experiência",
  "corp.metrics.years_val": "11+",
  "corp.metrics.build": "Anos construindo",
  "corp.metrics.build_val": "8+",
  "corp.metrics.tech_val": "20+",
  "corp.green.title": "Nossos datacenters",
  "corp.green.sub": "Usam 100% de energia renovável",
  "corp.green.body": "Construindo infraestrutura para o futuro.",
  "corp.green.cta": "Consultar hospedagem",
  "corp.brands.title": "Confiamos nos melhores fabricantes do setor",
  "corp.contact.title": "Contato",
  "corp.contact.support": "Suporte técnico 24/7",
  "corp.contact.support_email": "support@hashrate.space",
  "corp.contact.investors": "Relações com investidores",
  "corp.contact.investors_email": "build@hashrate.space",
  "corp.contact.sales": "Hospedagem e vendas",
  "corp.contact.sales_email": "sales@hashrate.space",
  "corp.contact.office": "Escritórios",
  "corp.contact.addr1": "Juan de Salazar 1857",
  "corp.contact.addr2": "Assunção – Paraguai · CEP 001527",
  "corp.contact.phones": "(+595) 991 907 308 · (+595) 993 358 387",
  "corp.contact.doc_title": "Contato — Hashrate Space",
  "corp.contact.meta_desc":
    "Dados de contato, e-mails e formulário para suporte, vendas e investidores — Hashrate Space.",
  "corp.partners.title": "Parceiros oficiais",
  "corp.partners.lede": "Alianças com fabricantes e fornecedores do ecossistema de mineração.",
  "corp.partners.luxor_aria": "Luxor — site externo (abre em nova aba)",
  "corp.faq.title": "Perguntas frequentes",
  "corp.faq.lede": "Políticas, envios e operação: a equipe responde pelos canais de contato.",
  "corp.faq.spot.kicker": "ASICs · Hospedagem · Paraguai",
  "corp.faq.spot.specs": "Orçamentos, estoque e logística conforme acordo. Respostas pelos canais oficiais.",
  "corp.faq.spot.acc_heading": "Respostas rápidas",
  "corp.faq.spot.img_alt": "Linha Antminer S21 — render de produto",
  "corp.faq.shop_cta": "Ver equipamentos",
  "corp.faq.contact_cta": "Contato",
  "corp.faq.q1": "Vocês enviam do Paraguai?",
  "corp.faq.a1":
    "Sim. Coordenamos frete e documentação conforme destino, incoterms e normas vigentes em cada operação.",
  "corp.faq.q2": "O equipamento inclui garantia?",
  "corp.faq.a2":
    "As condições dependem do fabricante e do contrato; em cada orçamento detalhamos cobertura e prazos.",
  "corp.faq.q3": "Oferecem hospedagem para mineradores?",
  "corp.faq.a3": "Temos capacidade em datacenters parceiros; a disponibilidade é confirmada ao solicitar orçamento.",
  "corp.faq.q4": "Como peço um orçamento?",
  "corp.faq.a4": "Na loja você monta a lista de equipamentos ou nos escreve pela seção de contato.",
  "corp.sales_banner.body":
    "Se você já tem experiência em mineração ou está começando, nossa equipe pode orientá-lo sobre operação, equipamentos e hospedagem na região.",
  "corp.how.title": "Como funciona?",
  "corp.how.lede":
    "A Hashrate Space aproxima você da mineração de Bitcoin com hardware validado e suporte humano — direto, sem enrolação.",
  "corp.how.step1_title": "Escolha seu minerador",
  "corp.how.step1_body":
    "Explore nosso catálogo de ASICs de alto desempenho. Escolha o hardware que cabe no seu orçamento e no seu objetivo.",
  "corp.how.step2_title": "Acompanhe e gerencie",
  "corp.how.step2_body":
    "Painel e relatórios para monitorar desempenho e gerenciar seus equipamentos quando quiser, de qualquer lugar.",
  "corp.how.step3_title": "Comece a minerar",
  "corp.how.step3_body":
    "Seu minerador faz hash para sua pool. A Hashrate ajuda e dá suporte — você não precisa ser especialista.",
  "corp.how.chart_legend": "Receita 24h",
  "corp.how.step1_img_alt": "Minerador ASIC — vista em perspectiva sobre fundo verde em degradê",
  "corp.how.step2_img_alt": "Mão segurando um smartphone com o site Hashrate Space na tela",
  "corp.how.step3_img_alt": "Painel escuro com gráfico de linha e meses no eixo inferior",
  "corp.company.title": "Empresa",
  "corp.company.body":
    "A Hashrate Space desenvolve e opera infraestrutura para mineração de Bitcoin na região, com foco em energia, confiabilidade e suporte próximo.",
  "services.doc_title": "Serviços de mineração e hospedagem — Hashrate Space",
  "services.meta_desc":
    "Serviços profissionais de mineração Bitcoin: infraestrutura, hospedagem gerenciada, logística internacional e manutenção técnica com suporte especializado.",
  "services.hero.title": "Plataforma de infraestrutura de alto desempenho e totalmente gerenciada",
  "services.hero.body":
    "A Hashrate Space é uma distribuidora líder de equipamentos de mineração cripto na América do Sul e oferece soluções de mineração para operações de qualquer escala.",
  "services.section.title": "Serviços",
  "services.card.asic": "Equipamentos de mineração ASIC",
  "services.card.network": "Conectividade de rede",
  "services.card.installation": "Instalação",
  "services.card.security": "Segurança física",
  "services.card.maintenance": "Manutenção e reparos",
  "services.card.insurance": "Seguro de equipamentos",
  "services.flow.title": "Como funciona?",
  "services.flow.body":
    "Se você procura a melhor hospedagem profissional para seus equipamentos de mineração, podemos ajudar.",
  "services.flow.aria": "Fluxo do serviço",
  "services.flow.purchase": "Compra",
  "services.flow.shipping": "Envio",
  "services.flow.customs": "Desembaraço aduaneiro",
  "services.flow.setup": "Setup e mineração",

  "company.doc_title": "Empresa – Hashrate Space",
  "company.meta_desc":
    "HRS GROUP S.A.: infraestrutura e HPC no Paraguai. Equipe de liderança da Hashrate Space — mineração Bitcoin e datacenters.",
  "company.intro.h3": "Por que somos diferentes",
  "company.intro.p1":
    "A HRS GROUP S.A. é uma empresa especializada em infraestrutura e computação de alto desempenho sediada no Paraguai. Oferecemos acesso a energia a baixo custo e mais de 11 anos de know-how em infraestrutura tecnológica. Nosso foco é fornecer aos clientes soluções completas e personalizadas que cubram todas as necessidades relacionadas a infraestrutura e datacenters de alta disponibilidade para mineração de criptomoedas.",
  "company.intro.p2":
    "Nossa proposta foca em criar um ecossistema de última geração em que os equipamentos de computação operam de forma automática e eficiente, gerando ganhos passivos depositados diretamente na sua carteira digital.",
  "company.intro.p3":
    "Com tecnologia avançada e abordagem inovadora, garantimos uma experiência excepcional e maximizada em rentabilidade. Cuidamos de tudo para que você só precise aproveitar os benefícios.",
  "company.intro.img_alt": "Infraestrutura e equipamentos ASIC em operação",
  "company.values.h3": "Nosso valor principal",
  "company.values.p1":
    "Somos uma empresa inovadora orientada a soluções, dedicada a dar acesso a tecnologias blockchain e inteligência artificial por meio de energia renovável e custos acessíveis.",
  "company.values.p2":
    "Nossa visão é transformar o setor tecnológico removendo barreiras por meio de uma infraestrutura tecnológica e energética global eficiente e acessível — impulsionando um futuro mais verde e rentável para o ecossistema.",
  "company.lead.h2": "Conheça a equipe de liderança",
  "company.lead.p":
    "Somos uma equipe multidisciplinar premiada com sede no Paraguai e raízes no Uruguai, apaixonada por criar infraestrutura inovadora e descentralizada. Trabalhamos com empresas e indivíduos para construir uma empresa sólida em que investidores e clientes confiem.",
  "company.team.dlg_close": "Fechar",
  "company.team.linkedin_aria": "Perfil no LinkedIn (abre em nova aba)",
  "company.team.linkedin_label": "LinkedIn",
  "company.team.read_bio": "Ver biografia",
  "company.m.fab.role": "Co-fundador",
  "company.m.fab.name": "Fabrizio Bianchi",
  "company.m.fab.b1":
    "Apaixonado por tecnologia e inovação, Fabrizio é um líder especializado em infraestrutura em larga escala e datacenters de alto desempenho. Com mais de 20 anos de experiência, foi pioneiro em mineração industrial de Bitcoin e criptomoedas no Uruguai, referência regional com visão global.",
  "company.m.fab.b2":
    "Seu espírito empreendedor e profundo conhecimento em hardware e software o levaram a explorar e implementar soluções inovadoras em tecnologias emergentes. Comprometido com a vanguarda, estuda e adota novas tendências para otimizar processos e gerar impacto positivo.",
  "company.m.jv.role": "Co-fundador",
  "company.m.jv.name": "Jose Luis Vila Soler",
  "company.m.jv.b1":
    "Licenciado em Administração de Empresas com mais de 15 anos de experiência em gestão de negócios, especializa-se em finanças, marketing, fidelização de clientes e business intelligence — com foco em análise estratégica de dados e geração de valor.",
  "company.m.jv.b2":
    "Impulsionado pelo empreendedorismo, diversificou sua trajetória investindo ativamente no setor agropecuário, desenvolvendo projetos em pecuária e agricultura.",
  "company.m.jv.b3a":
    "Durante um período nos Estados Unidos, explorou trading de ações e criptomoedas, despertando o interesse por tecnologia. Isso o levou à programação e à pesquisa em mineração de criptomoedas, culminando na criação do seu projeto mais recente: ",
  "company.m.jv.brand": "Hashrate Space",
  "company.m.jv.b3b": ".",
  "company.m.jv.b4":
    "Este projeto reflete sua dedicação a novas oportunidades, unindo dados, tecnologia e estratégia para soluções práticas e inovadoras. Com abordagem dinâmica, continua liderando iniciativas que abrem caminho no negócio e na tecnologia.",
  "company.m.af.role": "Co-fundador",
  "company.m.af.name": "Anthony Figueroa",
  "company.m.af.b1":
    "Engenheiro de sistemas e CTO movido por tecnologias transformadoras e inovação de alto impacto. Apaixonado por relacionamentos estratégicos, desafios complexos e alinhar visão de negócio à execução técnica para soluções escaláveis.",
  "company.m.af.b2":
    "Especializado em: Blockchain, IA e Machine Learning, Ciência de Dados, plataformas de e-learning, infraestrutura IoT e tecnologias em saúde.",
  "company.m.dg.role": "Executivo de vendas",
  "company.m.dg.name": "Damian Gómez",
  "company.m.dg.b1":
    "Lidera a área de Parcerias Estratégicas de Negócios na Hashrate, identificando, estruturando e consolidando alianças que impulsionam o crescimento sustentável. Conecta oportunidades em energia, tecnologia e finanças para expandir infraestrutura e operações de mineração de alto desempenho.",
  "company.m.dg.b2":
    "Sua capacidade de construir relações de longo prazo com investidores, fornecedores e parceiros foi decisiva para posicionar a Hashrate no ecossistema de mineração de Bitcoin na região. Combina pensamento estratégico, execução disciplinada e foco em valor para stakeholders.",
  "company.m.rg.role": "Desenvolvimento de negócios — LATAM",
  "company.m.rg.name": "Romina Garbino",
  "company.m.rg.b1":
    "Profissional focada em oportunidades comerciais e no fortalecimento da presença e parcerias da Hashrate na Argentina e na região. Impulsiona conexões entre empresas, investidores e o ecossistema de infraestrutura digital e ativos tecnológicos.",
  "company.m.rg.b2":
    "Ao longo da carreira, desenvolveu vínculos com comunidades, startups, parceiros e stakeholders do setor, atuando como ponte entre necessidades de negócio e soluções concretas.",
  "company.m.ab.role": "Desenvolvimento de negócios",
  "company.m.ab.name": "Augusto Biselli",
  "company.m.ab.b1":
    "Profissional focado em desenvolvimento estratégico de negócios, com experiência em oportunidades comerciais, parcerias e expansão de mercados. Destaca-se pela visão analítica, negociação e foco em resultados.",
  "company.m.ab.b2":
    "Participou ativamente da estruturação e execução de estratégias de crescimento, gerindo relações com parceiros, investidores e clientes corporativos — unindo pensamento estratégico à execução prática para transformar oportunidades em projetos rentáveis.",

  "filter.label": "Filtrar",
  "filter.all": "Todos",
  "filter.bitcoin": "Bitcoin",
  "filter.doge_ltc": "DOGE + LTC",

  "shelf.seemore": "Ver mais",
  "shelf.seemore_aria": "Ver mais — {{model}} — {{hash}}",
  "shelf.techspecs": "Dados técnicos do modelo",
  "shelf.add_title": "Adicionar à lista de orçamento (conta cliente ou administrador A/B)",

  "modal.close_win": "Fechar janela",
  "modal.detail_aria": "Detalhe do produto e solicitação",
  "modal.gallery": "Galeria do produto",
  "modal.no_photos": "Produto sem fotos",
  "modal.thumbs": "Vistas do produto",
  "modal.store_official": "Loja oficial",
  "modal.verified": "Verificado",
  "modal.store_sub": "Novo · Entrega conforme estoque e logística",
  "modal.price_note":
    "Preço referencial em USD. Impostos e logística conforme a operação. Valores sujeitos a variação de mercado e disponibilidade.",
  "modal.price_box_label": "Preço referencial",
  "modal.specs_aria": "Especificações técnicas",
  "modal.yield_title": "Rendimento estimado",
  "modal.yield_loading": "…",
  "modal.yield_daily": "Produção diária",
  "modal.yield_usdt": "Bruto USDT",
  "modal.yield_foot_loading": "…",
  "modal.yield_foot_ref": "Valores referenciais (catálogo).",
  "modal.cta_title": "Solicitar orçamento",
  "modal.email_btn": "Consultar por e-mail",
  "modal.wa_btn": "Consultar por WhatsApp",
  "modal.add_quote_aria": "Adicionar ao carrinho",
  "modal.host_title": "Hashrate Space",
  "modal.host_loc": "Hospedagem Paraguai",
  "modal.host_flag_aria": "Bandeira do Paraguai",
  "modal.host_tier1": "1–9 mineradores",
  "modal.host_tier2": "+10 mineradores",
  "modal.host_kwh1": "USD 0,078 / kWh",
  "modal.host_kwh2": "USD 0,076 / kWh",
  "modal.hashrate_share_title": "Comprar hashrate (fração de um equipamento)",
  "modal.hashrate_share_full": "100% — Equipamento completo",
  "modal.hashrate_share_of": "{{pct}}%",
  "modal.hashrate_share_btn": "+ Solicitar hashrate",
  "modal.hashrate_share_popover_title": "Escolha o % do mesmo equipamento",
  "modal.hashrate_share_add": "Adicionar esta fração",
  "modal.hashrate_share_add_short": "+ Solicitar hashrate",
  "modal.hashrate_share_add_disclaimer":
    "Ao comprar hashrate, você entra em uma solicitação sujeita à disponibilidade. A alocação não é imediata e pode implicar tempo de espera. Nossa equipe entrará em contato para seguir o processo.",
  "modal.hashrate_share_viewing": "Você está vendo {{pct}}% do hashrate deste mesmo minerador",
  "modal.hashrate_share_full_view": "Voltar",
  "modal.hashrate_share_back_aria": "Voltar à ficha com 100% do equipamento",
  "modal.hashrate_share_legal_title": "Esclarecimento sobre hashrate (mesma unidade física)",
  "modal.hashrate_share_legal_p1":
    "O equipamento {{model}} tem hashrate nominal de referência de {{full}} ao cotar a unidade completa (100%), conforme especificação típica de fábrica.",
  "modal.hashrate_share_legal_p2":
    "Neste orçamento você seleciona {{pct}}% do hashrate desse mesmo minerador, equivalente a {{portion}}. Não implica um segundo equipamento nem uma máquina adicional distinta.",
  "modal.hashrate_share_legal_p3":
    "Os preços referenciais, a potência indicada e os rendimentos estimados nesta tela são mostrados proporcionalmente ao percentual escolhido.",
  "modal.yield_foot_share": "Cifras de rendimento proporcionais ao % exibido.",
  "modal.mail.subject":
    "Orçamento marketplace ASIC — {{brand}} {{model}} {{hash}} ({{price}})",
  "modal.wa.body":
    "Olá, escrevo pelo hashrate.space e gostaria de solicitar orçamento: {{brand}} {{model}} {{hash}} — {{price}}.",

  "drawer.close_aria": "Fechar painel de orçamento",
  "drawer.close": "Fechar",
  "drawer.title": "Pedido de compra",
  "drawer.sub_one": "1 equipamento na sua lista",
  "drawer.sub_many": "{{n}} equipamentos na sua lista",
  "drawer.lede": "Preencha o carrinho com os equipamentos que desejar:",
  "drawer.hint.p1": "Para adicionar equipamentos e salvar seu orçamento no sistema,",
  "drawer.login_link": "faça login",
  "drawer.hint.p2": " com a sua conta; se não tiver uma conta, ",
  "drawer.hint.p3": "ou",
  "drawer.hint.p4": ", ou",
  "drawer.register_link": "crie uma nova",
  "drawer.hint.p5": ".",
  "drawer.pending_orders": "Pedidos pendentes",
  "drawer.view_my_orders_kicker": "Acompanhamento da consulta",
  "drawer.view_my_orders_btn": "Ver minha compra pendente",
  "drawer.view_my_orders_hint": "Status do ticket",
  "drawer.back_to_cart": "Voltar ao carrinho",
  "drawer.cart_policy_title": "Pedido em andamento",
  "drawer.cart_policy_text":
    "Uma conta tem apenas um pedido aberto por vez. Os equipamentos que você adicionar somam-se a esse pedido ao salvar; para começar de novo, cancele no acompanhamento e esvazie o carrinho.",
  "drawer.empty_title": "Sua lista está vazia",
  "drawer.empty_hint": "Adicione equipamentos com «+ Adicionar» na grade ou no detalhe do produto.",
  "drawer.empty_pending_order_link": "Você tem uma compra em acompanhimento — ver detalhe",
  "drawer.selected": "Equipamentos selecionados",
  "drawer.line_hashrate_share": "{{pct}}% hashrate — fração do mesmo equipamento",
  "drawer.remove": "Remover",
  "drawer.remove_aria": "Remover {{model}} da lista",
  "drawer.per_unit": " / unidade",
  "drawer.qty_aria": "Quantidade de {{model}}",
  "drawer.qty_minus": "Diminuir quantidade",
  "drawer.qty_plus": "Aumentar quantidade",
  "drawer.addons_aria": "Opções para {{model}}",
  "drawer.addons_hint": "Opcional (por u.): desmarque se não se aplicar instalação na fazenda ou garantia.",
  "drawer.setup": "Setup",
  "drawer.warranty": "Garantia",
  "drawer.per_u": "/ u.",
  "drawer.subtotal": "Subtotal",
  "drawer.total": "Total preço",
  "drawer.total_note": "Soma da lista · USD",
  "drawer.ref_label": "Sua referência",
  "drawer.next": "Próximo passo",
  "drawer.next_logged":
    "Gere o ticket para registrar a consulta no sistema. Você também pode nos escrever por e-mail ou WhatsApp.",
  "drawer.next_guest":
    "Faça login (cliente ou administrador A/B) para gerar o ticket e ver o status em «Pedidos pendentes».",
  "drawer.gen_ticket": "Gerar pedido de compra",
  "drawer.gen_ticket_update": "Atualizar pedido",
  "drawer.gen_busy": "Gerando ticket…",
  "drawer.gen_busy_update": "Salvando…",
  "drawer.err_ticket": "Não foi possível gerar o ticket.",
  "drawer.opening": "Abrindo…",
  "drawer.email": "E-mail",
  "drawer.wa": "WhatsApp",
  "drawer.email_aria": "Consultar por e-mail",
  "drawer.email_opening": "Abrindo e-mail",
  "drawer.wa_aria": "Consultar por WhatsApp",
  "drawer.wa_opening": "Abrindo WhatsApp",
  "drawer.login_cta": "Entrar ou cadastrar-se",
  "drawer.clear": "Esvaziar lista",
  "drawer.client": "cliente",
  "drawer.admin": "administrador A/B",
  "drawer.one_active_title": "Pedido em acompanhamento",
  "drawer.one_active_body":
    "Seu pedido aberto é carregado nesta lista: tudo o que você adicionar ou alterar salva no mesmo pedido e ticket. O detalhe completo está em «Meus pedidos».",
  "drawer.one_active_link": "Ir para Meus pedidos",
  "drawer.one_active_err":
    "Não foi possível atualizar o pedido. Verifique sua conexão ou tente de novo; se persistir, abra «Meus pedidos».",

  "login.back_catalog": "Voltar ao catálogo",
  "login.quote_title": "Orçamento na loja",
  "login.quote_blocked":
    "Você está logado como {{email}} (função {{role}}). O carrinho de orçamento está disponível com conta {{client}} ou {{admin}}. Com operador ou leitor é preciso usar outra sessão.",
  "login.quote_hint_from":
    "Encerre a sessão e entre com um usuário autorizado para orçamento, ou cadastre-se como cliente.",
  "login.quote_hint_other": "Você ainda pode ver o catálogo sem montar lista de orçamento com esta sessão.",
  "login.logout_switch": "Sair e entrar com outra conta",
  "login.hrs_home": "Ir ao início HRS (painel interno)",
  "login.kicker": "Loja online",
  "login.intro": "Faça login para montar sua lista e solicitar orçamento.",
  "login.intro_strong": "Faça login",
  "login.intro_after": "para montar sua lista e solicitar orçamento.",
  "login.form_title": "Entrar na sua conta",
  "login.user_label": "Usuário ou e-mail",
  "login.password": "Senha",
  "login.err_generic": "Erro ao entrar",
  "login.preparing": "Preparando…",
  "login.entering": "Entrando…",
  "login.submit": "Entrar",
  "login.back_shop": "Voltar à loja",
  "login.no_account": "Ainda não tem conta?",
  "login.register": "Cadastre-se",

  "orders.loading": "",
  "orders.back": "← Voltar ao catálogo",
  "orders.title": "Pedido pendente",
  "orders.title_record": "Consulta (histórico)",
  "orders.intro": "Acompanhamento do seu pedido enviado à equipe de vendas.",
  "orders.kpi": "{{n}} no processo",
  "orders.kpi_suffix": "no processo",
  "orders.load_err": "Não foi possível carregar os pedidos.",
  "orders.empty_no_active_title": "Você não tem uma consulta em andamento",
  "orders.empty_no_active_p":
    "Aqui só aparece seu pedido ativo (um por vez). Consultas canceladas ou fechadas não aparecem no carrinho; a equipe as vê na gestão de orçamentos.",
  "orders.empty_title": "Você ainda não tem consultas registradas.",
  "orders.empty_p1": "Monte sua lista no catálogo e toque em",
  "orders.empty_strong": "Gerar pedido de compra",
  "orders.empty_p2": "no carrinho.",
  "orders.card_items": "{{lines}} itens · {{units}} u.",
  "orders.updated": "Atualizado {{when}}",
  "orders.drawer_close": "Fechar",
  "orders.drawer_order_fallback": "Pedido #{{id}}",
  "orders.created_updated": "Criado {{created}} · Última atualização {{updated}}",
  "orders.channel": "Canal:",
  "orders.channel_portal": "Loja (ticket)",
  "orders.ref_total": "Preço total:",
  "orders.your_order": "Seu pedido",
  "orders.detail_meta_created": "Criado",
  "orders.detail_meta_updated": "Atualizado",
  "orders.detail_lines_count": "{{n}} item(ns)",
  "orders.footer_note": "Os preços podem variar conforme as condições de mercado.",
  "orders.contact_status_email_whatsapp":
    "Nossa equipe de vendas entrará em contato por WhatsApp no número ({{whatsapp}}) e por e-mail ({{email}}).",
  "orders.contact_status_email_phone":
    "Nossa equipe de vendas entrará em contato por telefone ({{phone}}) e por e-mail ({{email}}).",
  "orders.contact_status_email": "Nossa equipe de vendas entrará em contato por e-mail ({{email}}).",
  "orders.status.enviado_consulta": "Consulta enviada",
  "orders.status.en_gestion": "Em gestão",
  "orders.status.respondido": "Respondido",
  "orders.status.cerrado": "Fechado",
  "orders.status.descartado": "Descartado",
  "orders.search_label": "Buscar",
  "orders.search_placeholder": "Pedido, ticket ou status…",
  "orders.detail_lines_loading": "Carregando equipamentos do pedido…",
  "orders.detail_lines_summary":
    "Resumo: {{lines}} tipo(s) de equipamento · {{units}} u. · total {{total}} USD (linhas não listadas no servidor).",
  "orders.meta_records_one": "{{n}} registro",
  "orders.meta_records_other": "{{n}} registros",
  "orders.meta_filtered": "· {{n}} com o filtro atual",
  "orders.export_excel": "Exportar Excel",
  "orders.borrar_todo": "Apagar tudo",
  "orders.delete_one": "Excluir",
  "orders.delete_one_aria": "Excluir este pedido",
  "orders.delete_drawer": "Excluir pedido",
  "orders.delete_drawer_sub": "Remove este registro do seu histórico.",
  "orders.delete_confirm_one": "Excluir este pedido ({{order}})? Você não poderá recuperá-lo.",
  "orders.delete_confirm_all":
    "Excluir as {{n}} consultas/pedidos registrados na sua conta? (Apaga todos, não só os do filtro de busca.) A equipe deixará de vê-los no painel. Você não poderá recuperá-los.",
  "orders.delete_ok_one": "Pedido excluído.",
  "orders.delete_ok_one_detail": "{{order}} foi removido. Não aparecerá mais na sua lista nem no painel da equipe.",
  "orders.delete_ok_all": "Foram removidos {{n}} pedido(s) da sua conta. Não aparecerão mais na sua lista nem no painel da equipe.",
  "orders.delete_ok_all_toast":
    "Todos os seus pedidos foram excluídos com sucesso. Foram apagados {{n}} registro(s); não figuram mais na sua conta nem no painel da equipe.",
  "orders.delete_err": "Não foi possível excluir. Tente novamente.",
  "orders.delete_all_empty": "Não há pedidos para apagar.",
  "orders.modal_delete_order_title": "Excluir pedido",
  "orders.modal_delete_all_title": "Apagar todos os pedidos",
  "orders.modal_delete_one_before": "Excluir o pedido ",
  "orders.modal_delete_one_after": "? Você não poderá recuperá-lo.",
  "orders.modal_delete_all_before": "Você vai excluir ",
  "orders.modal_delete_all_after":
    " pedidos ou consultas da sua conta. Apaga todos os registrados, não só os que você vê com o filtro de busca.",
  "orders.modal_irreversible": "Esta ação não pode ser desfeita.",
  "orders.modal_cancel": "Cancelar",
  "orders.modal_confirm_delete": "Excluir",
  "orders.modal_deleting": "Excluindo…",
  "orders.row_ticket": "Ticket",
  "orders.row_status": "Status",
  "orders.row_items": "Itens / unidades",
  "orders.row_total": "Preço total",
  "orders.row_updated": "Última atualização",
  "orders.detail_btn": "Ver detalhe",
  "orders.back_to_list": "Voltar à lista",
  "orders.excel_sheet": "Minhas consultas",
  "orders.excel_empty": "Não há linhas para exportar com o filtro atual.",
  "orders.excel_ok": "Excel gerado.",
  "orders.clear_search": "Limpar",
  "orders.no_results_title": "Sem resultados",
  "orders.no_results_hint": "Tente outra busca ou limpe o filtro.",
  "orders.one_account_rule":
    "Uma conta = uma consulta em andamento. Se precisar mudar o pedido, cancele o pedido ativo e monte o carrinho de novo.",
  "orders.legacy_multi_pipeline":
    "Você tem mais de uma consulta em andamento. A loja só permite uma por vez: cancele as que não usar até restar uma só; depois poderá gerar outra pelo carrinho.",
  "orders.cancel_order": "Cancelar pedido",
  "orders.cancel_order_sub": "Libere o carrinho e gere uma nova consulta quando quiser.",
  "orders.cancel_order_aria": "Cancelar este pedido em andamento",
  "orders.modal_cancel_order_title": "Cancelar pedido em andamento",
  "orders.modal_cancel_order_before": "Você vai marcar como descartado o pedido ",
  "orders.modal_cancel_order_after":
    ". Poderá montar um carrinho novo e gerar outra consulta pelo catálogo. A equipe continuará vendo o registro como descartado.",
  "orders.modal_confirm_cancel_order": "Sim, cancelar pedido",
  "orders.modal_canceling": "Cancelando…",
  "orders.cancel_ok": "Pedido cancelado. Você já pode usar o carrinho de novo.",
  "orders.cancel_err": "Não foi possível cancelar. Tente novamente.",

  "reg.blocked_back": "Voltar ao catálogo",
  "reg.blocked_title": "Cadastro de cliente",
  "reg.blocked_body":
    "Você está logado como {{email}} (função {{role}}). Para criar uma conta cliente da loja, encerre a sessão primeiro.",
  "reg.blocked_title_alt": "Cadastro conta cliente",
  "reg.blocked_detail":
    "Você está logado como {{email}} (função {{role}}). Para se cadastrar como cliente na loja, encerre esta sessão primeiro (administradores já podem usar o carrinho com a conta).",
  "reg.blocked_from_quote":
    "Você veio para orçar: se tem conta admin A/B ou cliente, volte ao catálogo; senão, saia e cadastre-se.",
  "reg.blocked_else": "O cadastro nesta página cria apenas usuários com função cliente para a loja.",
  "reg.logout_continue": "Sair e continuar",
  "reg.hrs_home_short": "Ir ao início HRS",
  "ticket.summary_title": "Ticket gerado",
  "ticket.invoice_kicker": "Comprovante de consulta",
  "ticket.invoice_fine":
    "Documento referencial de orçamento · Não constitui nota fiscal nem comprovante de pagamento.",
  "ticket.summary_lede_before":
    "Sua consulta foi registrada. A equipe comercial pode vê-la no painel de pedidos e entrará em contato. Você pode acompanhar o status em",
  "ticket.summary_lede_after": ".",
  "ticket.order_lbl": "Pedido",
  "ticket.code_lbl": "Ticket",
  "ticket.meta_status": "Status",
  "ticket.meta_lines": "Linhas / unidades",
  "ticket.meta_units": "u.",
  "ticket.meta_total": "Total preço",
  "ticket.btn_orders": "Ver status no carrinho",
  "ticket.close": "Fechar",
  "pwd.show": "Mostrar senha",
  "pwd.hide": "Ocultar senha",
  "reg.aside_aria": "Benefícios",
  "reg.badge": "Loja HASHRATE SPACE",
  "reg.aside_title": "Crie sua conta e escolha seu equipamento de mineração com confiança",
  "reg.aside_lead":
    "Um único cadastro para montar seu pedido e acompanhar seus pedidos em um ambiente pensado para clientes de mineração Bitcoin.",
  "reg.aside_b1": "Listas de orçamento e atualizações do catálogo ASIC.",
  "reg.aside_b2": "Dados de envio e contato claros para agilizar sua compra.",
  "reg.aside_b3": "Acesso seguro com seu e-mail e senha.",
  "reg.hero_title": "Criar conta cliente",
  "reg.hero_lead": "Preencha o formulário para orçar equipamentos de mineração e gerenciar seus dados de contato.",
  "reg.card_kicker_lower": "Cadastro de nova conta",
  "reg.card_desc_long":
    "Preencha os campos com seus dados pessoais. Com sua conta você acessa o mundo da mineração de bitcoin e criptomoedas.",
  "reg.legend_account": "Sua conta",
  "reg.email_label": "E-mail",
  "reg.email_ph": "nome@gmail.com",
  "reg.pw_min": "Senha (mín. 6)",
  "reg.pw_confirm": "Confirmar senha",
  "reg.legend_personal": "Dados pessoais",
  "reg.label_nombre": "Nome",
  "reg.ph_nombre": "Nome completo",
  "reg.label_apellidos": "Sobrenome",
  "reg.ph_apellidos": "Sobrenome",
  "reg.legend_ship": "Local de envio",
  "reg.label_country": "País",
  "reg.country_placeholder": "Selecione seu país…",
  "reg.label_city": "Cidade",
  "reg.city_pick": "Selecione sua cidade…",
  "reg.city_need_country": "Escolha o país primeiro",
  "reg.city_other": "Outra cidade…",
  "reg.ph_city_other": "Nome da cidade",
  "reg.label_address": "Endereço",
  "reg.ph_address": "Rua, número, bairro",
  "reg.legend_id": "Documento de identidade",
  "reg.id_doc_type": "Tipo de documento",
  "reg.id_doc_num_ph": "Número do documento",
  "reg.legend_contact_block": "Contato",
  "reg.label_mobile": "Celular",
  "reg.dial_aria": "Código internacional",
  "reg.phone_ph": "(Ex. 981 123456)",
  "reg.err.password_short": "A senha deve ter pelo menos 6 caracteres.",
  "reg.err.password_mismatch": "As senhas não coincidem.",
  "reg.err.nombre": "Informe seu nome.",
  "reg.err.apellidos": "Informe seu sobrenome.",
  "reg.err.documento": "Informe o número do documento.",
  "reg.err.country": "Selecione seu país.",
  "reg.err.country_bad": "País inválido.",
  "reg.err.city": "Selecione sua cidade.",
  "reg.err.city_other": "Digite o nome da cidade.",
  "reg.err.address": "Informe seu endereço (rua, número, bairro…).",
  "reg.err.dial": "Selecione o código do país do celular.",
  "reg.err.dial_bad": "Código do país do celular inválido.",
  "reg.err.phone": "Informe um número de celular válido (apenas dígitos, sem repetir o código do país).",
  "reg.err.duplicate_fallback": "Este e-mail já está cadastrado.",
  "reg.err.register_fail": "Não foi possível cadastrar. Tente novamente.",
  "reg.dup_heading": "Este e-mail já tem uma conta",
  "reg.dup_login": "Entrar na loja",
  "reg.dup_sgi": "Acesso ao sistema interno (SGI)",
  "reg.dup_security_note":
    "Por segurança, não compartilhe sua senha por e-mail, WhatsApp nem ligações. Se não conseguir entrar, contate um administrador por um canal oficial.",
  "reg.footer_have_login": "Já tem conta? Entrar",
  "reg.kicker": "CADASTRO DE NOVA CONTA",
  "reg.title": "Formulário de cadastro",
  "reg.desc": "Preencha os dados para criar sua conta de cliente na loja online.",
  "reg.submit": "Criar minha conta",
  "reg.submit_busy": "Criando conta…",
  "reg.have_account": "Já tem conta?",
  "reg.login_link": "Entrar",
  "reg.back_shop": "← Voltar à loja",
};
